[{"raw":{},"required":["Filename","Size"],"package":"python3-zope.exceptions","source":"zope.exceptions","version":"4.6-1","section":"universe/zope","priority":"extra","architecture":"all","depends":["python3-pkg-resources","python3-zope.interface","python3:any"],"installedSize":94,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Zope exceptions for Python 3","homepage":"https://github.com/zopefoundation/zope.exceptions","filename":"pool/universe/z/zope.exceptions/python3-zope.exceptions_4.6-1_all.deb","size":16230,"md5":"8f392fb496fb600b786d82329058322f","sha1":"5ce8eb941cd1bef4ce6188ec81021e516304bbce","sha256":"781c600a4e24abcd6ccbd6b1d381cbf26b0f54efaaee0632924503d2efbb83fa","sha512":"b18242a9c8b2fb6ec2caa4b074e0e8fca05d3376fa91a2658b45ff4cebf36c0ce12db68773e0b63b58d74916dc2e7aba5700fa7440dac2b13913d79631577a21","descriptionMd5":"6659ed22b4d66ce3d4e50aa50de55f19"}]