{"raw":{},"required":["Filename","Size"],"package":"python3-zope.exceptions","source":"zope.exceptions","version":"4.0.8-1","section":"universe/zope","priority":"extra","architecture":"all","depends":["python3-pkg-resources","python3-zope.interface","python3:any (>= 3.3.2-2~)"],"installedSize":90,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Zope exceptions for Python 3","homepage":"http://pypi.python.org/pypi/zope.exceptions","filename":"pool/universe/z/zope.exceptions/python3-zope.exceptions_4.0.8-1_all.deb","size":14696,"md5":"b263c7c0db643122296834cdd7b87829","sha1":"b3fd3189b9883e32dba77d8dd8174dfef386112b","sha256":"5317883e74a588091b8a6854c17ff976814f4d620cf763cb53075a9173ed3c87","descriptionMd5":"6659ed22b4d66ce3d4e50aa50de55f19"}