{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-django-dbconn-retry",
	"source": "python-django-dbconn-retry",
	"version": "0.1.6-3",
	"section": "universe/python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-django",
		"python3:any"
	],
	"installedSize": 36,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "reconnect on a failed database (Python3 version)",
	"homepage": "https://github.com/jdelic/django-dbconn-retry/",
	"filename": "pool/universe/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.6-3_all.deb",
	"size": 9312,
	"md5": "99395ce0167ddd769b2f2434cb9ce743",
	"sha1": "c9d406e1745009389c3e42a87309186628ee8a97",
	"sha256": "a499f2a3351697a82c041ecf2cd718ce3338d812f60cbaf3ab040a495b53e42c",
	"sha512": "b7b6bbfc40eeb219c61f23c04cee81e39255da209f17fab14c7f66526f85a0ef685da382489b9037e49d4bcfba1f33151f9eecb74b1d0c9b0e583dfd8a3919ff",
	"descriptionMd5": "e6f9867f49ff9821aa4e414064f0370a"
}