{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-django-dbconn-retry",
	"source": "python-django-dbconn-retry",
	"version": "0.1.5-1",
	"section": "universe/python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-django",
		"python3:any (>= 3.3.2-2~)"
	],
	"installedSize": 37,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "reconnect on a failed database (Python3 version)",
	"homepage": "https://github.com/jdelic/django-dbconn-retry/",
	"filename": "pool/universe/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.5-1_all.deb",
	"size": 8568,
	"md5": "08bac9f37d2f6487689db032634c7312",
	"sha1": "7f21055bb129d1252ca3d2338352c520e66f38cc",
	"sha256": "a4d48ecf0d64b914c5e07b6874da0bf7f34f921101eba020cb93c9ef04beab72",
	"descriptionMd5": "e6f9867f49ff9821aa4e414064f0370a"
}